general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    color = rgba(111118ff)
}

label {
    monitor =
    text = $TIME
    color = rgba(a6adc8ff)
    font_size = 42

    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(8f849eff)
    font_size = 14

    position = 0, 25
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 260, 40
    position = 0, -45

    dots_center = true
    fade_on_empty = false

    inner_color = rgba(181825ff)
    outer_color = rgba(cba6f7ff)
    font_color = rgba(cdd6f4ff)

    outline_thickness = 2
    rounding = 6

    placeholder_text = <span foreground="##6c7086">Password...</span>

    halign = center
    valign = center
}
